server:
  port: 8760

eureka:
  instance:
    hostname: localhost1
    prefer-ip-address: false
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost2:8759/eureka/

spring:
  application:
    name: eureka-server