eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
  zipkin:
    base-url: http://172.30.3.58:9411
#  cloud:
#    loadbalancer:
#      retry:
#        enabled: true
#  sleuth:
#    sampler:
#      probability: 1
zuul:
  routes:
    api-a:
      path: /ribbon/**
      erviceId: service-ribbon
    api-b:
      path: /feign/**
      serviceId: service-feign

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 5
        #       为什么这个地方配置的requestVolumeThreshold没用 好像就是三次不行就不管了
        #        forceClosed: true
        sleepWindowInMilliseconds: 20000
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000

service-feign:
  ribbon:
    ReadTimeout: 4000
    ConnectTimeout: 30000

service-ribbon:
  ribbon:
    ReadTimeout: 5500
    ConnectTimeout: 30000

