server:
  port: 8770

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          username:
          password:
          search-paths: respo
      label: master
  zipkin:
    base-url: http://172.30.3.58:9411
#  sleuth:
#    sampler:
#      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/