server:
  port: 8759

eureka:
  instance:
    hostname: localhost2
    prefer-ip-address: false
  client:
    #    registerWithEureka: false
    #    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost1:8760/eureka/

spring:
  application:
    name: eureka-server